Song.create(title: "Song one", released: true, release_year: 2005, artist_name: "Artist one", genre: "Some genre")
Song.create(title: "Song two", released: true, release_year: 1978, artist_name: "Artist one", genre: "Some genre")
Song.create(title: "Song three", released: true, release_year: 2016, artist_name: "Artist one", genre: "Other genre")
Song.create(title: "Song four", released: true, release_year: 2000, artist_name: "Artist two", genre: "Other genre")
Song.create(title: "Song five", released: true, release_year: 1987, artist_name: "Artist two", genre: "Other genre")
Song.create(title: "Song six", released: true, release_year: 1999, artist_name: "Artist three", genre: "That genre")
Song.create(title: "Song seven", released: false, artist_name: "Artist three", genre: "This genre")